# Generated by Django 6.0.4 on 2026-04-21 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('risk_level', models.CharField(choices=[('ZAYIN', 'ZAYIN'), ('TETH', 'TETH'), ('HE', 'HE'), ('WAW', 'WAW'), ('ALEPH', 'ALEPH')])),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Аномалия',
                'verbose_name_plural': 'Аномалии',
            },
        ),
        migrations.CreateModel(
            name='EGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=10)),
                ('effect', models.TextField()),
                ('anomalies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fandom.anomalies')),
            ],
            options={
                'verbose_name': 'Дар EGO',
                'verbose_name_plural': 'Дары EGO',
            },
        ),
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='anomalies_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('anomalies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fandom.anomalies')),
            ],
            options={
                'verbose_name': 'Картинка аномалии',
                'verbose_name_plural': 'Картинки аномалий',
            },
        ),
    ]
