# Generated by Django 6.0.4 on 2026-04-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fandom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalies',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
